<<<<<<< HEAD
# Generated by Django 3.2.2 on 2021-05-19 19:07
=======
# Generated by Django 3.2.2 on 2021-05-20 03:07
>>>>>>> upstream/main

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('audio', models.FileField(upload_to='')),
<<<<<<< HEAD
                ('duration', models.DurationField(verbose_name='')),
=======
                ('duration', models.DurationField()),
>>>>>>> upstream/main
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('exercise_name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
