# Generated by Django 3.2.2 on 2021-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_card_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='thumbnail',
            field=models.ImageField(upload_to=None),
        ),
    ]
