# Generated by Django 3.2.2 on 2021-05-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210523_2019'),
        ('core', '0004_alter_card_thumbnail'),
    ]

    operations = [
    ]
