# Generated by Django 3.2.2 on 2021-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20210527_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
