# Generated by Django 3.2.2 on 2021-06-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_history_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='duration',
            field=models.DurationField(),
        ),
    ]
