# Generated by Django 3.2.2 on 2021-06-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_exercisecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='history/images'),
        ),
    ]
