# Generated by Django 3.2.2 on 2021-06-21 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='card_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='thumbnail',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Weekstreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('day_count', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
