# Generated by Django 3.2.2 on 2021-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_history_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='card_id',
            field=models.IntegerField(default=0),
        ),
    ]
