# Generated by Django 3.2.2 on 2021-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_history_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
