# Generated by Django 3.2.2 on 2021-06-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_streaks'),
        ('core', '0012_alter_exercisecount_count'),
    ]

    operations = [
    ]
