# Generated by Django 3.2.2 on 2021-07-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_audiodata_output_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.FileField(default='', upload_to='outputaud/audio')),
            ],
        ),
    ]
