# Generated by Django 3.2.2 on 2021-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210618_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaks',
            name='day_count',
            field=models.BooleanField(default=False),
        ),
    ]
