# Generated by Django 3.2.2 on 2021-06-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_history_card_id'),
        ('core', '0014_auto_20210618_2349'),
    ]

    operations = [
    ]
